version: '3.8'

services:
  mysql:
    image: mysql:8.0 # Specify a version for better stability
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: blockchain_price_tracker
      MYSQL_USER: blockchain_price_user
      MYSQL_PASSWORD: blockchain_price_password
    ports:
      - "3306:3306" # Host port 3306 mapped to container's port 3306
    volumes:
      - blochain_price_tracker_mysql_data:/var/lib/mysql # Persistent data storage

volumes:
  blochain_price_tracker_mysql_data: # Volume to persist MySQL data
